apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-web-app
  labels:
    app: node-web-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: node-web-app
  template:
    metadata:
      labels:
        app: node-web-app
    spec:
      containers:
        - name: node-web-app
          image: node:14
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: node-web-app-service
spec:
  selector:
    app: node-web-app
  ports:
    - name: http
      port: 80
      targetPort: 3000
  type: LoadBalancer
