# apiVersion: podmig.dcn.ssu.ac.kr/v1
# kind: Podmigration
# metadata:
#   name: podmigration-sample
# spec:
#   # Add fields here
#   foo: bar
apiVersion: livemigration.liqo.io/v1alpha1
kind: LiveMigration
metadata:
  name: my-webapp
  namespace: liqo-demo
  labels:
    app: my-webapp
spec:
  replicas: 1
  action: live-migration
  snapshotPath: /var/lib/kubelet/migration
  sourcePod: my-webapp-5856f58698-bcbmr
  destHost: rome-worker
  selector:
    matchLabels:
      app: my-webapp
      namespace: liqo-demo
  # template:
  #   metadata:
  #     labels:
  #       app: video
  #   spec:
  #     containers:
  #     - name: vlc
  #       image: tuongvx/vlc-app:latest
  #       ports:
  #       - containerPort: 8080
  #         protocol: TCP
  #       #args: ["big_buck_bunny.mp4","--loop","--sout", "#transcode{scodec=none}:http{mux=ffmpeg{mux=flv},dst=:8080/}"]
  #     nodeSelector:
  #       kubernetes.io/hostname: worker2
