apiVersion: v1
kind: Namespace
metadata:
  name: liqo-demo
---
apiVersion: v1
kind: Service
metadata:
  name: my-webapp
  namespace: liqo-demo
  labels:
    app: my-webapp
spec:
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: my-webapp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-webapp
  namespace: liqo-demo
  labels:
    app: my-webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-webapp
  template:
    metadata:
      labels:
        app: my-webapp
    spec:
      volumes:
      - name: task-pv-storage
        persistentVolumeClaim:
          claimName: task-pv-claim
      containers:
      - name: task-pv-container
        image: docker.io/nginx:latest
        ports:
        - containerPort: 80
          name: "http-server"
        volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: task-pv-storage
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: task-pv-volume
  namespace: liqo-demo
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: task-pv-claim
  namespace: liqo-demo  
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
