apiVersion: v1
kind: Pod
metadata:
  name: red
  labels:
    app: rubyapp
  annotations:
    snapshotPolicy: "restore"
    snapshotPath: "/var/lib/kubelet/migration/fff/tuongvx"
spec:
  containers:
  - name: tuong
    image: tylerfowler/superset
    ports:
    - containerPort: 8088
      protocol: TCP
  nodeSelector:
    kubernetes.io/hostname: worker1