apiVersion: v1
kind: Service
metadata:
  name: registry-service
  namespace: default
spec:
  selector:
    run: registry
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: NodePort
  externalIPs:
    - 172.16.3.75

