repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v3.0.0-alpha.6"
    hooks:
      - id: prettier

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
      - id: requirements-txt-fixer
      - id: trailing-whitespace

  - repo: local
    hooks:
      - id: build-go
        name: Build Go file
        entry: go build -o live-migration-operator api-server/cmd/main.go
        language: system
        types: [file]
        files: '\.go$'
        stages: [commit]
