apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  namespace: liqo-demo
spec:
  containers:
    - name: tomcat
      image: docker.io/leonardopoggiani/checkpoint-images:tomcat-pod
      imagePullPolicy: Always
      ports:
        - containerPort: 8080
