apiVersion: v1
kind: Pod
metadata:
  name: tomcat-pod
  namespace: default
spec:
  containers:
    - name: tomcat
      image: docker.io/tomcat:latest
      imagePullPolicy: Always
      ports:
        - containerPort: 8080
  nodeSelector:
    kubernetes.io/hostname: leonardo-controller
