apiVersion: v1
kind: Pod
metadata:
  name: tomcat-pod
  namespace: default
spec:
  containers:
    - name: tomcat
      image: docker.io/tomcat:latest
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 8080
