apiVersion: v1
kind: Pod
metadata:
  name: tomcat-pod
  namespace: liqo-demo
spec:
  shareProcessNamespace: true
  containers:
    - name: tomcat
      image: docker.io/library/tomcat:latest
      imagePullPolicy: IfNotPresent
