apiVersion: v1
kind: PersistentVolume
metadata:
  name: checkpoint-pv
  namespace: liqo-demo
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/checkpoints/
  storageClassName: checkpoint-storage
