apiVersion: v1
kind: Pod
metadata:
  name: dummy-pod
  namespace: offloaded
spec:
  containers:
  - name: dummy-container
    image:  quay.io/adrianreber/counter:blog
  nodeName: poggianifedora-1.novalocal
