apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dummy-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: test-csi-provisioner
---
apiVersion: v1
kind: Pod
metadata:
  name: dummy-pod
spec:
  containers:
   - name: dummy-container
     image: docker.io/library/nginx
     volumeMounts:
       - mountPath: /var/lib/www/html
         name: checkpoint-pvc
  volumes:
   - name: checkpoint-pvc
     persistentVolumeClaim:
       claimName: dummy-pvc
       readOnly: false