apiVersion: v1
kind: Pod
metadata:
  name: checkpoint-provisioner
  namespace: kube-system
spec:
  containers:
  - name: provisioner
    image: docker.io/leonardopoggiani/checkpoint-provisioner:latest
    volumeMounts:
    - name: checkpoint-volume
      mountPath: /data
  volumes:
  - name: checkpoint-volume
    hostPath:
      path: /mnt/disks/checkpoint
