apiVersion: v1
kind: Pod
metadata:
  name: wordpress
spec:
  volumes:
    - name: mysql-persistent-storage
      emptyDir: {}
  containers:
    - name: mysql
      image: mysql:5.7
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: "wordpress"
        - name: MYSQL_DATABASE
          value: "wordpress"
      volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
    - name: wordpress
      image: wordpress:5.7.1-php8.0-apache
      env:
        - name: WORDPRESS_DB_HOST
          value: "127.0.0.1"
        - name: WORDPRESS_DB_NAME
          value: "wordpress"
        - name: WORDPRESS_DB_USER
          value: "root"
        - name: WORDPRESS_DB_PASSWORD
          value: "wordpress"
      ports:
        - containerPort: 80
      volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
