# apiVersion: podmig.dcn.ssu.ac.kr/v1
# kind: Podmigration
# metadata:
#   name: podmigration-sample
# spec:
#   # Add fields here
#   foo: bar
apiVersion: podmig.dcn.ssu.ac.kr/v1
kind: Podmigration
metadata:
  name: test
  labels:
    name: test
spec:
  replicas: 1
  action: "live-migration"
  snapshotPath: /var/lib/kubelet/migration
  sourcePod: redis
  destHost: worker2
  selector:
    podmig: dcn