apiVersion: v1
kind: Pod
metadata:
  name: restored-nginx
  namespace: liqo-demo
spec:
  containers:
    - name: web
      image: docker.io/leonardopoggiani/checkpoint-images:web
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 80
