apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: liqo-demo
spec:
  containers:
    - name: web
      image: localhost/checkpoint-image:latest
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 80
