apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: liqo-demo
spec:
  containers:
    - name: web
      image: docker.io/library/nginx
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 80
