apiVersion: v1
kind: Pod
metadata:
  name: multi-container-pod
  namespace: liqo-demo
spec:
  containers:
    - name: web
      image: docker.io/library/nginx
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 80
    - name: db
      image: docker.io/library/mysql:latest
      imagePullPolicy: IfNotPresent
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: "password"
        - name: MYSQL_DATABASE
          value: "app"
        - name: MYSQL_USER
          value: "app"
        - name: MYSQL_PASSWORD
          value: "password"
      volumeMounts:
        - name: db-data
          mountPath: /var/lib/mysql
  volumes:
    - name: db-data
      emptyDir: {}