apiVersion: v1
kind: Pod
metadata:
  name: multi-container-pod
  namespace: liqo-demo
spec:
  shareProcessNamespace: true
  containers:
  - name: web-server
    imagePullPolicy: IfNotPresent
    image: docker.io/nginx:latest
    ports:
    - containerPort: 80
    volumeMounts:
    - name: shared-data
      mountPath: /usr/share/nginx/html
  - name: file-watcher
    image: docker.io/busybox:latest
    imagePullPolicy: IfNotPresent
    volumeMounts:
    - name: shared-data
      mountPath: /watch
    command: ["/bin/sh", "-c", "while true; do find /watch -type f -exec cat {} +; done"]
  volumes:
  - name: shared-data
    emptyDir: {}
  nodeSelector:
    kubernetes.io/hostname: poggiani-1-master
