apiVersion: v1
kind: Pod
metadata:
  name: vlc-pod
spec:
  containers:
    - name: vlc-container
      image: ghcr.io/leonardopoggiani/video:latest
      command:
        - /usr/bin/vlc
      args:
        - /video/video.mp4
      volumeMounts:
        - name: video-file
          mountPath: /video
  volumes:
    - name: video-file
      hostPath:
        path: /home/poggio/Documenti/GitHub/live-migration-operator/config/samples/migration-example/video.mp4