apiVersion: v1
kind: Pod
metadata:
  name: video
  labels:
    app: video
spec:
  volumes:
    - name: video
      hostPath:
        path: /video
  containers:
    - name: vlc
      image: quay.io/galexrt/vlc:latest
      ports:
        - containerPort: 8080
          protocol: TCP
      #args: ["big_buck_bunny.mp4","--loop","--sout", "#transcode{scodec=none}:http{mux=ffmpeg{mux=flv},dst=:8080/}"]
      args: ["data/video.mp4", "--intf=dummy", "-I", "dummy", "-q", "--loop", "--sout", "#transcode{scodec=none}:http{mux=ffmpeg{mux=flv},dst=:8080/}"]
      volumeMounts:
        - name: video
          mountPath: /data  # in the container filesystem
  nodeSelector:
    kubernetes.io/hostname: leonardo-dev