name: build

env:
  SSH_AUTH_SOCK: /tmp/ssh_agent.sock

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: "0 10 * * 1" # run "At 10:00 on Monday"
  workflow_call:
    inputs:
      skipTests:
        description: "Skip tests, useful when there is a dedicated CI job for tests"
        default: false
        required: false
        type: boolean

jobs:
  run:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: read
      packages: write
    strategy:
      fail-fast: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          repository: leonardopoggiani/live-migration-operator
          token: ${{ secrets.TOKEN }}

      - name: Set GOFLAGS environment variable
        run: export GOFLAGS="-mod-timeout=600"

      - name: Copy SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-agent -a "$SSH_AUTH_SOCK" > /dev/null
          ssh-add ~/.ssh/id_rsa

      - name: Set up Git auth
        run: |
          echo "machine github.com login leonardopoggiani password ${{ secrets.TOKEN }}" > ~/.netrc
          chmod 600 ~/.netrc

      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: ">=1.20.1"

      - name: Set GOPRIVATE environment variable
        run: echo "export GOPRIVATE=github.com/leonardopoggiani" >> $GITHUB_ENV

      - name: Delete go.mod
        run: |
          rm go.mod
          rm go.sum
          go mod init

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y libbtrfs-dev libdevmapper-dev libgpgme-dev libseccomp-dev
          git remote set-url origin git@github.com:leonardopoggiani/live-migration-operator.git
          go env -w GOPRIVATE=github.com/leonardopoggiani/*
          git config --global --add url."git@github.com:".insteadOf "https://github.com/"

      - name: Install main dependencies
        run: |
          go get github.com/leonardopoggiani/live-migration-operator/storage-provisioner
          go get github.com/leonardopoggiani/live-migration-operator

      - name: Update dependencies
        run: |
          go get -u github.com/containers/buildah
          go mod tidy

      - name: Go Format
        run: gofmt -s -w .

      - name: Go Build
        run: go build -o live-migration-operator .

      - name: Go Compile Tests
        if: ${{ inputs.skipTests }}
        run: go test -exec /bin/true ./...

      - name: Go Test
        if: ${{ !inputs.skipTests }}
        run: go test -v -count=1 -race -shuffle=on -coverprofile=coverage.txt ./... -timeout 20m

      - name: Go Benchmark
        if: ${{ !inputs.skipTests }}
        run: go test -v -shuffle=on -run=- -bench=. -benchtime=1x ./...
